### ISSUE TITLE
Editor doesn't load in FF Linux

### ISSUE THREAD

**Issue by seotts** [LLK/scratchx#35] opened 2015-06-05 16:06 UTC
Here is the console:
![image](https://cloud.githubusercontent.com/assets/4612592/8010085/46fcb04e-0b7b-11e5-8409-102954706953.png)

**Comment by 2jour** [comment] 2015-12-13 22:52
Can reproduce on Ubuntu.

**Comment by MrYsLab** [comment] 2015-12-14 13:29
Duplicate of #24

**Comment by thisandagain** [comment] 2016-01-06 17:00
Tracking in #24

**Closed by thisandagain** 2016-01-06 17:00 UTC
Labels: needs discussion
